cosmos/testnets

README.md
gaia-4000/config.toml
gaia-4000/genesis.json

Update testnet with new `gaiad` and `gaiacli` commands

Updated README with new testnet docs

---

README.md

readme: typos, consistency fixes

---

README.md

Updated docs to merge *before* new testnet launch

Added content to old gaia-4000 README

---

README.md

Revert "Added content to old gaia-4000 README"

---

gaia-6001/genesis.json
gaia-tardigrade/genesis.json

Please comment on this PR to make sure that we, as a validator community, come to consensus.

Proposed genesis block for gaia-6001

---

README.md

Should only be merged when we want to switch testnet instructions to current develop.

changes to cli for current sdk develop

---

gaia-8000-rc0/README.md
gaia-8000-rc0/cwgoes.json

Internal testnet for gaia-8000

Add gaia-8000-rc0

---

gaia-8000-rc0/asripal.json

Aditya gentx file

---

gaia-8000-rc0/greg.json

Added greg gentx for gaia-8000-rc0

---

latest/genesis.json

Update latest to the correct genesis

---

gaia-9000/genesis.json
latest/genesis.json

Solve for param renaming

---

gaia-9001/config.toml
latest/config.toml

added gaia-9001 config.toml example

---

gaia-10k/dokia.json

adding Dokia

---

gaia-12k/genesis.json
latest/genesis.json

Add gaia-12k genesis

---

gaia-12k/genesis.json
latest/genesis.json

Fix gaia-12k

---

gaia-13k/13007/gentxs/mandalorian.json

Added gentx

---

gaia-13k/13007/gentxs/BlockOps.json

Add BlockOps gentx

---

gaia-13k/13007/genesis.json

- Params copied from 13006
- Denom changed to `umuon`
- Fixed crisis fee
- Do we need to add more accounts for faucets? 
- Need to decide on genesis time.

Gaia 13007 Genesis

---

README.md

fix broken docs link

---

bigbang-1/README.md
bigbang-1/phase-1/README.md

Bigbang fixes

---

scripts/verify-gentx.sh

Fix gentx validation

---

bigbang-1/genesis.json
scripts/generate-genesis.sh

Add genesis

---

bigbang-1/phase-1/README.md

added witval peer

---

bigbang-1/phase-1/README.md

Add explorer, faucet links

---

bigbang-1/stargate-upgrade.md

Bigbang testnet: add stargate upgarde details

---

bigbang-1/stargate-upgrade.md

updated proposal details

---

bigbang-1/stargate-upgrade.md

Update bigbang-1 explorer links

---

bigbang-1/cosmovisor-setup.md
bigbang-1/stargate-upgrade.md

Stargate upgrade instructions

---

bigbang-1/app.toml
bigbang-1/stargate-migration.md

added app.toml and chain-id

---

bigbang-1/stargate-migration.md

Signed-off-by: kaustubhkapatral <kaustubh.kapatral@gmail.com>

updated instructions

---

.gitattributes
.gitignore
v6-Vega/.gitignore
v6-Vega/README.md
v6-Vega/exported_unmodified_genesis.json.gz
v6-Vega/local-testnet/README.md
v6-Vega/local-testnet/modified_genesis_local_testnet/genesis.json.gz
v6-Vega/local-testnet/priv_validator_key_val1.json
v6-Vega/local-testnet/priv_validator_key_val2.json
v6-Vega/public-testnet/README.md
v6-Vega/public-testnet/modified_genesis_public_testnet/diff.md
v6-Vega/public-testnet/modified_genesis_public_testnet/genesis.json.gz
v6-Vega/public-testnet/replace_ref.sh

merge v6-vega testnet repo to testnet repo

---

README.md
v6-Vega/README.md
v7-theta/README.md
v7-theta/devnet/README.md
v7-theta/local-testnet/README.md
v7-theta/public-testnet/README.md
v7-theta/public-testnet/UPGRADES.md

Includes details of the theta testnet upgrade

V7 theta upgrade details

---

v7-theta/public-testnet/README.md

Use seeds instead of persistent peers with minor changes

---

public/README.md

Fix link to public testnet genesis file.

Update testnet genesis url

---

public/UPGRADES.md

Updated `public/UPGRADES.md` with a link to the v8.0.0-rc3 release page.

Add link to release page

---

public/README.md
public/join-public-testnet-cv.sh
public/join-public-testnet.sh

Added port 443 to relevant https endpoints.

Update https endpoints for public testnet

---

public/README.md
public/UPGRADES.md
public/join-public-testnet-cv.sh
public/join-public-testnet.sh

Updated testnet version to `v8.0.0-rc3`.

Public testnet upgraded to v8

---

README.md
replicated-security/README.md
replicated-security/SCHEDULE.md
replicated-security/provider-1/README.md
replicated-security/provider-1/join-rs-provider-cv.sh
replicated-security/provider-1/join-rs-provider.sh
replicated-security/provider-1/provider-1-genesis.json
replicated-security/timeout-1/README.md
replicated-security/timeout-2/README.md
replicated-security/timeout-3/README.md
replicated-security/timeout-3/join-rs-timeout-3.sh
replicated-security/timeout-3/timeout-3-genesis.json

Added information on how to join the provider chain and upcoming chain launches.

RS Testnet launch

---

devnet/README.md
public/README.md
public/UPGRADES.md
public/join-public-testnet-cv.sh
public/join-public-testnet.sh

Updated READMEs and scripts for `v8.0.0-rc5`.

Updated data for v8-rc5 release

---

replicated-security/CONSUMER_LAUNCH_GUIDE.md

Adding a guide for consumer chain teams who are looking to join RS testnet

Add initial consumer chain guide

---

replicated-security/README.md
replicated-security/SCHEDULE.md
replicated-security/provider/README.md
replicated-security/provider/join-rs-provider-cv.sh
replicated-security/provider/join-rs-provider.sh
replicated-security/provider/provider-genesis.json

Reset the provider chain:
* Changed chain ID from `provider-1` to `provider`
* Updated genesis file
* Updated bash scripts

Restart provider-1 as provider

---

replicated-security/README.md
replicated-security/SCHEDULE.md
replicated-security/slasher/README.md
replicated-security/slasher/join-rs-slasher-cv.sh
replicated-security/slasher/join-rs-slasher.sh
replicated-security/slasher/proposal-slasher.json
replicated-security/slasher/slasher-genesis-without-ccv.json

Add slasher chain details.
Spawn time: 2023-02-03 15:00 UTC

Slasher chain launch scheduled

---

replicated-security/slasher/join-rs-slasher-cv.sh
replicated-security/slasher/join-rs-slasher.sh

Comment out the lines that download the genesis file until the spawn time is reached.

Update slasher bash scripts

---

replicated-security/README.md
replicated-security/SCHEDULE.md
replicated-security/slasher/README.md

Set slasher chain status to "started"

Slasher chain started

---

replicated-security/baryon-1/README.md
replicated-security/baryon-1/baryon-1-genesis-without-ccv.json
replicated-security/baryon-1/join-rs-baryon-1.sh
replicated-security/baryon-1/proposal-baryon-1.json

Neutron consumer chain required files, description and scripts

add neutron baryon chain details

---

replicated-security/README.md
replicated-security/SCHEDULE.md

Update RS testnet readme and schedule content

Add baryon-1 to schedule

---

replicated-security/README.md
replicated-security/SCHEDULE.md
replicated-security/slasher/README.md
replicated-security/slasher/proposal-stop-slasher.json

Updated schedule, added slashing timeline to `slasher` chain timeline.

Slasher chain stopped

---

replicated-security/baryon-1/baryon-1-genesis.json

Add Neutron baryon genesis

---

replicated-security/noble-1/proposal-noble-1.json

Fixing an invalid key in the proposal.

proposal invalid key

---

replicated-security/README.md
replicated-security/SCHEDULE.md
replicated-security/baryon-1/README.md
replicated-security/provider/README.md

Add `noble-1` consumer chain launch to schedule: Feb 9, 2023

Schedule noble-1 launch

---

public/README.md
public/UPGRADES.md
public/join-public-testnet-cv.sh
public/join-public-testnet.sh

Update Cosmos Hub Public Testnet to v9

Testnet v9 rc3 post upgrade

---

replicated-security/noble-1/README.md
replicated-security/noble-1/create-genesis.sh
replicated-security/noble-1/noble-1-genesis.json

genesis with ccv

---

replicated-security/README.md
replicated-security/SCHEDULE.md
replicated-security/noble-1/README.md

Updated docs to show `noble-1` is online now.

noble-1 chain is live

---

local/README.md
public/README.md

Added a warning regarding folder names when using Cosmovisor to handle upgrades.

Cosmovisor version notes

---

replicated-security/provider/README.md
replicated-security/provider/join-rs-provider-cv.sh
replicated-security/provider/join-rs-provider.sh

Updated README and bash scripts.

Upgrade RS provider chain to v9.0.0-rc7

---

replicated-security/CONSUMER_LAUNCH_GUIDE.md

Updated `CONSUMER_LAUNCH_GUIDE.md` under replicated security.

Added consumer onboarding details

---

replicated-security/baryon-1/v0.3.0_upgrade.md

This PR contains instructions for Neutron network (baryon-1)

baryon-1 network upgrade instructions

---

replicated-security/neutron-rehearsal-fix-1/README.md

Updated seed node ID
Added two persistent peers

Update peer info for rehearsal-fix-1

---

replicated-security/README.md
replicated-security/baryon-1/README.md

* Update stopped and live chains list
* Add note regarding Neutron rehearsal chains

Update chains status

---

replicated-security/pion-1/README.md
replicated-security/provider/README.md

Added clients, connections, and channels for the `provider` and `pion-1` chains.

Add pion-1 IBC data

---

public/join-public-testnet-cv.sh
public/join-public-testnet.sh

Remove min_gas_prices setting from state sync block

---

replicated-security/SCHEDULE.md
replicated-security/duality-rehearsal-1/README.md
replicated-security/duality-rehearsal-1/join-rs-duality-rehearsal-1-cv.sh
replicated-security/duality-rehearsal-1/join-rs-duality-rehearsal-1.sh
replicated-security/provider/README.md

- Added checkmark to schedule table
- Updated scripts with seed node and correct genesis url
- Added IBC data for duality-rehearsal-1

Duality launch updates

---

replicated-security/SCHEDULE.md

pion-1 upgraded to v1.0.2

---

replicated-security/SCHEDULE.md
replicated-security/pion-1/README.md
replicated-security/pion-1/join-rs-pion-1.sh
replicated-security/provider/README.md

* Updated schedule
* Added IBC data
* Updated genesis URL in script file

pion-1 relaunch updates

---

replicated-security/duality-rehearsal-1/README.md
replicated-security/duality-rehearsal-1/join-rs-duality-rehearsal-1-cv.sh
replicated-security/duality-rehearsal-1/join-rs-duality-rehearsal-1.sh

Update to add new seed node ID.
We created a new node when our previous node failed, and that gave it a new ID. We do hope to and would like to improve our process to not change IDs in the future when possible.

update duality-rehearsal-1 seed node

---

replicated-security/stride-ics-testnet-two-1/readme.md

* e7a01bcdb0f192cb028638ccd25f02f9f8b73ad4 -> ed3fcf9512ee136a03b58a7cd1d21b0e002de06f
* upload linux binary

Update commit hash

---

replicated-security/SCHEDULE.md

Schedule the Composable sovereign-consumer changeover rehearsal for Sep 27, 2023

Add composable rehearsal

---

local/README.md
local/previous-local-testnets/v12/README.md
public/README.md
public/UPGRADES.md
replicated-security/SCHEDULE.md
replicated-security/provider/README.md

* Release testnet upgrade height: `17996550`
* RS testnet provider chain upgrade height: `3313600`

Schedule v13 upgrade

---

replicated-security/banksy-testnet-3/README.md
replicated-security/banksy-testnet-3/Readme.md
replicated-security/banksy-testnet-3/genesis-without-ccv.json
replicated-security/banksy-testnet-3/proposal.json

Add banksy-testnet-3 initial RS testnet registration.

Add banksy-testnet-3

---

local/previous-local-testnets/v13/README.md
public/UPGRADES.md
replicated-security/provider/README.md

Updated:
* Local testnet
* Public testnet (`theta-testnet-001`) upgrades
* RS testnet (`provider`) readme

Schedule v14 upgrade

---

public/README.md
public/UPGRADES.md
replicated-security/SCHEDULE.md
replicated-security/provider/README.md

* Set halt height of 18876500 for `theta-testnet-001`
* Set halt height of 3977100 for `provider`

Schedule v14.0.0-rc1 upgrade

---

replicated-security/SCHEDULE.md
replicated-security/pion-1/README.md
replicated-security/pion-1/join-rs-pion-1.sh

* Current version: v2.0.1
* minimum-gas-prices: 0untrn

pion-1 upgraded to v2.0.1

---

replicated-security/provider/join-rs-provider-cv.sh
replicated-security/provider/join-rs-provider.sh

Add min gas prices to provider script

---

local/previous-local-testnets/v14/README.md
public/README.md
public/UPGRADES.md

Upgrade release testnet to v15

---

public/README.md
replicated-security/pion-1/README.md
replicated-security/provider/README.md

Updated the Hypha block explorer site to point to explorer.polypore.xyz

Updated block explorer links

---

public/UPGRADES.md
public/join-public-testnet-cv.sh
public/join-public-testnet.sh
replicated-security/SCHEDULE.md
replicated-security/provider/README.md
replicated-security/provider/join-rs-provider-cv.sh
replicated-security/provider/join-rs-provider.sh

Release/Theta testnet: Feb 20, 2024
Replicated Security testnet: Feb 21, 2024

Schedule v15.0.0-rc1 upgrades

---

public/UPGRADES.md
replicated-security/SCHEDULE.md
replicated-security/provider/README.md

theta-testnet-001: `20519000`
provider: `5425200`

Set halt heights for v15 rc3 upgrade

---

public/UPGRADES.md
replicated-security/SCHEDULE.md
replicated-security/provider/README.md
testnet-wednesdays/gameday01/README.md
testnet-wednesdays/gameday02/README.md

* Set v15.1.0 upgrade heights for both `provider` and `theta-testnet-001`
* Post instructions for game day

2024-03-27 Testnet Wednesday

---

isle/tasks.md

Added approx. timestamps to day 3 tasks.

Updated task criteria

---

README.md
interchain-security/Testnet_Incentives_Program.md

Added explainer sheet for TIP. Slight changes to README in main repo

Tip info updates

---

testnet-wednesdays/demoday11/README.md

Sign blocks in test-butterfly-1

Add task 2

---

legacy/bigbang-1/stargate-migration.md

Fixed a typo in stargate-migration.md, improving the accuracy and professionalism of the documentation. This ensures a cleaner and more readable file.

Typo fix stargate-migration.md

---

interchain-security/pion-1/sample-app.toml
interchain-security/pion-1/sample-config.toml

Add app.toml and config.toml for pion-1

Sample config files for pion
