cosmos/testnets

- gaia-6000/genesis.json
New genesis file that makes all the online validators from gaia-5001 into genesis validators
> Updated genesis

- README.md
> Updates to gaia10k

- README.md
Gaia 13005's genesis URL and Gaia 13006's were the same , so Gaia 13005's was fixed.
> Fix the Gaia 13005's genesis URL

- .github/workflows/verify-gentx.yaml
> Fix ga script

- bigbang-1/stargate-migration.md
> added migration info

- README.md
- v6-Vega/README.md
we don't need vega on the main readme anymore right?
> Update README.md remove vega

- devnet/README.md
Added a link to this section in the devnet README:
https://github.com/hyphacoop/cosmos-ansible/tree/main/examples#join-the-rho-devnet
> Add link to devnet example in cosmos-ansible

- replicated-security/README.md
- replicated-security/SCHEDULE.md
- replicated-security/consumer-1/README.md
- replicated-security/consumer-1/consumer-1-genesis-without-ccv.json
- replicated-security/consumer-1/join-rs-consumer-1-cv.sh
- replicated-security/consumer-1/join-rs-consumer-1.sh
- replicated-security/consumer-1/proposal-consumer-1.json
- replicated-security/timeout-1/README.md
- replicated-security/timeout-2/README.md
- replicated-security/timeout-3/README.md
The proposal to create the consumer-1 chain has passed.
Added the following for `consumer-1`:
- Spawn time
- Genesis file without CCV state
- Reference binary file
- Scripts to setup a node with and without Cosmovisor
Updated the schedule and RS readme to show that timeout-1 has now stopped.
> Add details for consumer-1 chain

- replicated-security/README.md
- replicated-security/SCHEDULE.md
- replicated-security/consumer-1/README.md
- replicated-security/timeout-1/README.md
- replicated-security/timeout-2/README.md
- replicated-security/timeout-3/README.md
- Set all consumer chains launched in week 1 to "stopped"
- Add upgrade binary event
- Remove date from slasher chain launch
> Update RS testnet schedule

- devnet/README.md
- public/README.md
- public/join-public-testnet-cv.sh
- public/join-public-testnet.sh
Updated README and bash scripts with `v8.0.0`.
> Update Cosmos Hub public testnet to v8.0.0

- public/README.md
- public/join-public-testnet-cv.sh
- public/join-public-testnet.sh
- replicated-security/provider/README.md
- replicated-security/provider/join-rs-provider-cv.sh
- replicated-security/provider/join-rs-provider.sh
The following chains have been updated to Gaia `v9.0.0-rc6`:
- Cosmos Hub Public Testnet (`theta-testnet-001`)
- Replicated Security Testnet `provider` chain
> Upgrade public testnets to v9.0.0-rc6

- replicated-security/neutron-rehearsal-fix-1/join-rs-neutron-rehearsal-1.sh
Bash script now has this seed node: `4336ea0b53080b0e50860417ab9a8a86d3eaecca@p2p.rehearsal.ntrn.tech:26656`
> Update seed node in bash script

- public/README.md
- public/UPGRADES.md
- public/join-public-testnet-cv.sh
- public/join-public-testnet.sh
- replicated-security/SCHEDULE.md
- replicated-security/provider/README.md
- replicated-security/provider/join-rs-provider-cv.sh
- replicated-security/provider/join-rs-provider.sh
* Updated READMEs, upgrade schedules, and scripts to join the `theta-testnet-001` and `provider` chains.
* Closes #430 and #431
> Upgraded testnets to Gaia v10

- public/UPGRADES.md
- replicated-security/SCHEDULE.md
- replicated-security/provider/README.md
Upgrading release testnet and provider chain of the RS testnet.
> Set Gaia v11 upgrade heights

- public/README.md
- public/UPGRADES.md
- public/join-public-testnet-cv.sh
- public/join-public-testnet.sh
- replicated-security/SCHEDULE.md
- replicated-security/provider/README.md
- replicated-security/provider/join-rs-provider-cv.sh
- replicated-security/provider/join-rs-provider.sh
The release testnet and provider chain of RS testnet are now running Gaia `v11.0.0-rc0`.
> Testnets Upgraded to v11

- local/README.md
- public/README.md
- public/UPGRADES.md
- public/join-public-testnet-cv.sh
- public/join-public-testnet.sh
- replicated-security/SCHEDULE.md
- replicated-security/provider/README.md
- replicated-security/provider/join-rs-provider-cv.sh
- replicated-security/provider/join-rs-provider.sh
Updated the following:
* Release testnet upgrades, readme, and scripts
* RS testnet schedule, provider chain readme and scripts
* Local testnet upgrade instructions use v12.0.0
> V12 upgrade complete

- public/README.md
- public/UPGRADES.md
- public/join-public-testnet-cv.sh
- public/join-public-testnet.sh
- replicated-security/provider/README.md
- replicated-security/provider/join-rs-provider-cv.sh
- replicated-security/provider/join-rs-provider.sh
Release testnet and RS testnet (`provider` chain) upgraded to v13.0.0-rc0
> Gaia v13 upgrade complete

- replicated-security/ethera_9000-1/consumer-addition-proposal.sh
- replicated-security/ethera_9000-1/create-ccv-genesis.sh
- replicated-security/ethera_9000-1/proposal-ethera_9000-1.json
- replicated-security/ethera_9000-1/validators_start_guide.md
This PR contains further files for Aether rehearsal network.
This PR create:
- `validators_start_guide.md`
- Guide on how to start Aether nodes
- `consumer-addition-proposal.sh` 
- Script used to create the consumer proposal
- `create-ccv-genesis.sh`
- This pulls the `ethera_9000-1` ccv and add it to genesis
This PR update:
- `proposal-ethera_9000-1.json`
- Removes the persistent word from the proposal
> Update Aether rehearsal network

- isle/day-1.md
- isle/day-2.md
Remove running consumer chains 3 hours before the following day's events
> Adjust offboarding times

- interchain-security/pion-1/README.md
Add instructions on how to adjust app.toml if Slinky is turned off to avoid missing blocks.
> Update pion-1 README for Slinky config

- release/README.md
The `theta-testnet-001` chain will halt at block height `24,791,000`.
> Release testnet halt height

- legacy/vega/README.md
**Fix typo: reccommended → recommended in README.md**
This pull request addresses a minor typo in the README file. Specifically:
- Corrected "reccommended" to "recommended" for accuracy and professionalism.
---
```diff
- A reccommended trusted block height is "current height - 1000."
+ A recommended trusted block height is "current height - 1000."
> **Fix typo: reccommended → recommended in README.md**
